import React, type { Component, ErrorInfo, ReactNode, useEffect } from 'react'
import { act, render, renderHook, waitFor } from '@testing-library/react'
import { Provider, useAtom, useAtomValue, useSetAtom } from 'jotai/react'
import { atom, createStore, getDefaultStore } from 'jotai/vanilla'
import { atomFamily } from '../src/atomFamily'
